# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datagen.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rdatagen.proto\x12\x07\x64\x61tagen" \n\x0e\x44\x61taGenRequest\x12\x0e\n\x06n_data\x18\x01 \x01(\x05"-\n\x0f\x44\x61taGenResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t"\x1b\n\x19MeasurePerformanceRequest"+\n\x1aMeasurePerformanceResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x32\xf9\x01\n\x0e\x44\x61taGenService\x12_\n\x12MeasurePerformance\x12".datagen.MeasurePerformanceRequest\x1a#.datagen.MeasurePerformanceResponse"\x00\x12>\n\x07\x44\x61taGen\x12\x17.datagen.DataGenRequest\x1a\x18.datagen.DataGenResponse"\x00\x12\x46\n\rDataGenStream\x12\x17.datagen.DataGenRequest\x1a\x18.datagen.DataGenResponse"\x00\x30\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "datagen_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DATAGENREQUEST._serialized_start = 26
    _DATAGENREQUEST._serialized_end = 58
    _DATAGENRESPONSE._serialized_start = 60
    _DATAGENRESPONSE._serialized_end = 105
    _MEASUREPERFORMANCEREQUEST._serialized_start = 107
    _MEASUREPERFORMANCEREQUEST._serialized_end = 134
    _MEASUREPERFORMANCERESPONSE._serialized_start = 136
    _MEASUREPERFORMANCERESPONSE._serialized_end = 179
    _DATAGENSERVICE._serialized_start = 182
    _DATAGENSERVICE._serialized_end = 431
# @@protoc_insertion_point(module_scope)
