# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hifuku.distributed.datagen_pb2 as datagen__pb2


class DataGenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MeasurePerformance = channel.unary_unary(
            "/datagen.DataGenService/MeasurePerformance",
            request_serializer=datagen__pb2.MeasurePerformanceRequest.SerializeToString,
            response_deserializer=datagen__pb2.MeasurePerformanceResponse.FromString,
        )
        self.DataGen = channel.unary_unary(
            "/datagen.DataGenService/DataGen",
            request_serializer=datagen__pb2.DataGenRequest.SerializeToString,
            response_deserializer=datagen__pb2.DataGenResponse.FromString,
        )
        self.DataGenStream = channel.unary_stream(
            "/datagen.DataGenService/DataGenStream",
            request_serializer=datagen__pb2.DataGenRequest.SerializeToString,
            response_deserializer=datagen__pb2.DataGenResponse.FromString,
        )


class DataGenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MeasurePerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DataGen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DataGenStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MeasurePerformance": grpc.unary_unary_rpc_method_handler(
            servicer.MeasurePerformance,
            request_deserializer=datagen__pb2.MeasurePerformanceRequest.FromString,
            response_serializer=datagen__pb2.MeasurePerformanceResponse.SerializeToString,
        ),
        "DataGen": grpc.unary_unary_rpc_method_handler(
            servicer.DataGen,
            request_deserializer=datagen__pb2.DataGenRequest.FromString,
            response_serializer=datagen__pb2.DataGenResponse.SerializeToString,
        ),
        "DataGenStream": grpc.unary_stream_rpc_method_handler(
            servicer.DataGenStream,
            request_deserializer=datagen__pb2.DataGenRequest.FromString,
            response_serializer=datagen__pb2.DataGenResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "datagen.DataGenService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DataGenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MeasurePerformance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/datagen.DataGenService/MeasurePerformance",
            datagen__pb2.MeasurePerformanceRequest.SerializeToString,
            datagen__pb2.MeasurePerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DataGen(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/datagen.DataGenService/DataGen",
            datagen__pb2.DataGenRequest.SerializeToString,
            datagen__pb2.DataGenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DataGenStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/datagen.DataGenService/DataGenStream",
            datagen__pb2.DataGenRequest.SerializeToString,
            datagen__pb2.DataGenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
